name: Deploy [main] to Staging

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  call:
    name: Build and Push
    uses: ledgelabs/ledge-chat/.github/workflows/deploy.yml@main
    with:
      env: staging
